# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: channellist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='channellist.proto',
  package='LEYc',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x11\x63hannellist.proto\x12\x04LEYc\"\x87\x01\n\x07\x43hannel\x12\x0e\n\x06\x63_name\x18\x01 \x02(\t\x12\x0e\n\x06\x63_link\x18\x02 \x01(\t\x12)\n\x06\x63_desc\x18\x03 \x01(\x0b\x32\x19.LEYc.Channel.Description\x1a\x31\n\x0b\x44\x65scription\x12\x10\n\x08\x63_desc_1\x18\x01 \x01(\t\x12\x10\n\x08\x63_desc_2\x18\x02 \x01(\t\"-\n\x0b\x43hannelList\x12\x1e\n\x07\x63hannel\x18\x01 \x03(\x0b\x32\r.LEYc.Channel')
)




_CHANNEL_DESCRIPTION = _descriptor.Descriptor(
  name='Description',
  full_name='LEYc.Channel.Description',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c_desc_1', full_name='LEYc.Channel.Description.c_desc_1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_desc_2', full_name='LEYc.Channel.Description.c_desc_2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=163,
)

_CHANNEL = _descriptor.Descriptor(
  name='Channel',
  full_name='LEYc.Channel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='c_name', full_name='LEYc.Channel.c_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_link', full_name='LEYc.Channel.c_link', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='c_desc', full_name='LEYc.Channel.c_desc', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHANNEL_DESCRIPTION, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=163,
)


_CHANNELLIST = _descriptor.Descriptor(
  name='ChannelList',
  full_name='LEYc.ChannelList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='LEYc.ChannelList.channel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=210,
)

_CHANNEL_DESCRIPTION.containing_type = _CHANNEL
_CHANNEL.fields_by_name['c_desc'].message_type = _CHANNEL_DESCRIPTION
_CHANNELLIST.fields_by_name['channel'].message_type = _CHANNEL
DESCRIPTOR.message_types_by_name['Channel'] = _CHANNEL
DESCRIPTOR.message_types_by_name['ChannelList'] = _CHANNELLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Channel = _reflection.GeneratedProtocolMessageType('Channel', (_message.Message,), dict(

  Description = _reflection.GeneratedProtocolMessageType('Description', (_message.Message,), dict(
    DESCRIPTOR = _CHANNEL_DESCRIPTION,
    __module__ = 'channellist_pb2'
    # @@protoc_insertion_point(class_scope:LEYc.Channel.Description)
    ))
  ,
  DESCRIPTOR = _CHANNEL,
  __module__ = 'channellist_pb2'
  # @@protoc_insertion_point(class_scope:LEYc.Channel)
  ))
_sym_db.RegisterMessage(Channel)
_sym_db.RegisterMessage(Channel.Description)

ChannelList = _reflection.GeneratedProtocolMessageType('ChannelList', (_message.Message,), dict(
  DESCRIPTOR = _CHANNELLIST,
  __module__ = 'channellist_pb2'
  # @@protoc_insertion_point(class_scope:LEYc.ChannelList)
  ))
_sym_db.RegisterMessage(ChannelList)


# @@protoc_insertion_point(module_scope)
